### PR TITLE
Added Parse Server hosting providers

### PR DESCRIPTION
**Pull request by rihadavid**
Parse Server hosting providers are popping up and I believe that this is what lot of us are looking for. I believe we should support these new services by placing this section on top of the page - because they will probably need to gain attention to be able to provide their services for us.

### CODE REVIEW

**Comment by relatedcode** [comment]
As far as I see we already have a category for that, called Parse Server providers. Please add new providers there (one by one). Thanks!

**Comment by rihadavid** [comment]
Sorry but I disagree. AWS, Azure, IBM, Heroku etc. is something entirely different. They have migration guide explaining how YOU can deploy your Parse Server instance on their infrastructure, they do not provide MANAGED hosting. They do not provide parse server uptime, maintenance, upgrades, support. They don't get your instance up and running automatically like parse.com did, you still must take care of the backend. Parse hosting providers take care about your parse server instance from migration to uptime guarantee. It  works the same way as parse.com did. Do you see the difference?

**Comment by relatedcode** [comment]
Ok. Let's do this. But we should plate this new category at the end of the page. Furthermore we should move the other providers (if exists) to the new category. Would you be so kind to manage the changes? Thanks!

**Comment by relatedcode** [comment]
My only asking: the changes should be crystal clear. I mean what is happening. Thanks!

**Comment by rihadavid** [comment]
Ok, thanks! See #254

**Pull request closed without merging**
