### PR TITLE
Fixed FatFractal link

### PR DESCRIPTION
**Pull request by shawkinaw**
Fixed FatFractal link.

### CODE REVIEW

**Comment by relatedcode** [comment]
Let's check the service later again. Thanks!

**Comment by shawkinaw** [comment]
OK, thank you, appreciate it. Just feel dumb for messing up the link.

**Comment by relatedcode** [comment]
No problem. I will check the details in the future. Thanks!

**Comment by shawkinaw** [comment]
Thanks. Just to be clear, our service is very robust and has been running for years, I just typed the wrong URL for the index, so I'd really appreciate it if you could put the entry back with the corrected address.

**Comment by relatedcode** [comment]
Added. :)

**Comment by shawkinaw** [comment]
Thank you! And thanks for putting together this repo, it's nice having a list of all the BaaS providers.

**Pull request closed without merging**
