### PR TITLE
Added Oracle Mobile Cloud Service

### PR DESCRIPTION
**Pull request by chriscmuir**
Added Oracle Mobile Cloud Services under the General purpose providers
section.

My first commit to Github, apologies if I make a newbie mistake.

### CODE REVIEW

**Comment by relatedcode** [comment]
Thanks! :)

**Comment by chriscmuir** [comment]
No worries - thanks for the opportunity to contribute & great effort in compiling the list for all to benefit.  It looks like I've done everything, let me know if there is anything I need to do at my end to get the change into the master.

**Comment by relatedcode** [comment]
Ok. Thanks! :)

**Comment by chriscmuir** [comment]
I guess that was a polite was of asking, saying I can see you've merged the changes, I don't see the entry for Oracle Mobile Cloud Service in the README.md master.  Did I make a mistake?

**Comment by relatedcode** [comment]
No, everything is ok. Thanks again.

**Comment by chriscmuir** [comment]
I still don't see the Oracle entry in the master README.md?  I take it there is a mistake or you've chosen not to include it?

CM.

**Pull request merged**
