### PR TITLE
Updated ParseGround to reflect name change to SashiDo

### PR DESCRIPTION
**Pull request by rkreager**
Updated the ParseGround entry to reflect their name change to SashiDo

### CODE REVIEW

**Comment by pivanov** [comment]
👍

**Comment by mignev** [comment]
👍

**Comment by mignev** [comment]
cc @relatedcode

**Comment by relatedcode** [comment]
Thanks! :)

**Comment by mignev** [comment]
Thanks!

**Comment by rkreager** [comment]
Thank you!

**Pull request merged**
