### PR TITLE
Added Syncano

### PR DESCRIPTION
**Pull request by rihadavid**

### CODE REVIEW

**Comment by mshusek** [comment]
I think it should be set as the real-time providers because of channel future.

**Comment by relatedcode** [comment]
As far as I see this is not exactly what we are trying to collect here. Thanks anyway.

**Comment by mshusek** [comment]
@relatedcode I worked with that BaaS in previous project and i think it is very familiar to parse. You can write your business logic in other language (eg. python, not only in JS), create scheduler jobs, custom permission and freemium plan.

**Comment by rihadavid** [comment]
@relatedcode Yeah I think it's actually one of the better solutions, I just can't use it because it does not support Xamarin. But is is very interesting and I think it should be here.

**Comment by relatedcode** [comment]
@mshusek @rihadavid Added. :)

**Pull request closed without merging**
