### PR TITLE
Add FatFractal

### PR DESCRIPTION
**Pull request by shawkinaw**
Added FatFractal link and description.

### CODE REVIEW

**Comment by relatedcode** [comment]
Thanks! :)

**Comment by shawkinaw** [comment]
Someone removed this, why?

**Comment by relatedcode** [comment]
@shawkinaw Sorry, but this service seems a little raw for me. Let's check later. Thanks!

**Comment by shawkinaw** [comment]
@relatedcode Yeah sorry, I mistyped the link. Should be http://fatfractal.com. Should I submit another PR?

**Pull request merged**
