### PR TITLE
Adding ShepHertz App42

### PR DESCRIPTION
**Pull request by RajeevRShephertz**

### CODE REVIEW

**Comment by relatedcode** [comment]
This is already added as AppWarp. Thanks anyway.

**Comment by RajeevRShephertz** [comment]
Thanks for your revert and addition of AppWarp in Gaming Backend Services. Why I made a request to add App42 platform in General Services is because AppWarp is primarily for game developers focusing on multiplayer gaming engine whereas App42 focuses on app development providing all the services a developer needs including all that Parse provided and much more. You may refer to this link: http://blogs.shephertz.com/2016/02/08/shephertz-app42-vs-parse/

It would be great if you make an addition in General Services. Thanks in advance.

**Comment by relatedcode** [comment]
Done. :)

**Comment by RajeevRShephertz** [comment]
Thank you so much for your quick response and addition. :)

**Comment by relatedcode** [comment]
:)

**Pull request merged**
